name = "akiprisaye-web"
compatibility_date = "2025-11-17"

# This is the configuration for Cloudflare Pages
[pages]
# The command to build your project
build_command = "npm run build"
# The directory where the built assets are located
build_output_dir = "dist"
