name = "akiprisaye-web"
compatibility_date = "2025-11-17"

[build]
command = "npm install && npm run build"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "latest"

pages_build_output_dir = "dist"
